// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PartsControlSystem.Data;

#nullable disable

namespace PartsControlSystem.Migrations
{
    [DbContext(typeof(PostgreAppDbContext))]
    [Migration("20260219094229_AddActivityCurrentProcess")]
    partial class AddActivityCurrentProcess
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PartsControlSystem.Models.ImportData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .HasColumnType("text")
                        .HasColumnName("activity");

                    b.Property<string>("BIPHMoldNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("biph_mold_no");

                    b.Property<string>("ChangeMaterial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("change_material");

                    b.Property<string>("ChildPartcode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("child_partcode");

                    b.Property<string>("ControlNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("control_no");

                    b.Property<DateTime>("DateImported")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_imported");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("MoldMaker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mold_maker");

                    b.Property<string>("MotherMoldCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mother_moldcode");

                    b.Property<string>("NewModel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_model");

                    b.Property<string>("NewToolingLocalization")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_tooling_localization");

                    b.Property<string>("NonConcurrent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("non_concurrent");

                    b.Property<string>("Other4M")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("other_4m");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("partname");

                    b.Property<string>("ReasonOfChange")
                        .HasColumnType("text")
                        .HasColumnName("reason_of_change");

                    b.Property<string>("RenewalAdditionalMold")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("renewal_additional_mold");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("section");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supplier");

                    b.Property<string>("SupplierChangeLocalization")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supplier_change_localization");

                    b.Property<string>("SupplierMoldNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supplier_mold_no");

                    b.Property<string>("ToolingCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tooling_category");

                    b.Property<string>("ToolingManagement")
                        .HasColumnType("text")
                        .HasColumnName("tooling_management");

                    b.Property<string>("ToolingType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tooling_type");

                    b.Property<string>("TransferTooling")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transfer_tooling");

                    b.HasKey("Id");

                    b.ToTable("import_data");
                });

            modelBuilder.Entity("PartsControlSystem.Models.LeadTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("activity");

                    b.Property<decimal>("LeadTimeValue")
                        .HasColumnType("numeric")
                        .HasColumnName("lead_time");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("section");

                    b.HasKey("Id");

                    b.ToTable("LeadTimes");
                });

            modelBuilder.Entity("PartsControlSystem.Models.MP2_ToolingQuotationRequestApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ActualDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ControlNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentProcess")
                        .HasColumnType("text");

                    b.Property<string>("InputBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("mp2_tooling_qoutation_request");
                });

            modelBuilder.Entity("PartsControlSystem.Models.MP2_ToolingRequestOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ActualDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ControlNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentProcess")
                        .HasColumnType("text");

                    b.Property<string>("InputBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TRFNo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("mp2_tooling_request_order");
                });

            modelBuilder.Entity("PartsControlSystem.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartsCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("PartsControlSystem.Models.UpdateActivityData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("activity");

                    b.Property<decimal?>("Actual")
                        .HasColumnType("numeric")
                        .HasColumnName("actual");

                    b.Property<int?>("ApprovalLeadTime")
                        .HasColumnType("integer")
                        .HasColumnName("approval_lead_time");

                    b.Property<string>("ControlNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("control_no");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<int?>("FabricationLeadTime")
                        .HasColumnType("integer")
                        .HasColumnName("fabrication_lead_time");

                    b.Property<DateTime?>("LimitDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("limit_date");

                    b.Property<string>("NeedNoNeed")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("need_no_need");

                    b.Property<DateTime?>("PartsShortageDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("parts_shortage_date");

                    b.Property<int?>("RemainingDaysUntilLimit")
                        .HasColumnType("integer")
                        .HasColumnName("remaining_days_until_limit");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("result");

                    b.Property<DateTime?>("ResultEmailDateToSupplier")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("result_email_date_to_supplier");

                    b.Property<string>("ResultPassedFailed")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("result_passed_failed");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("section");

                    b.Property<decimal?>("Target")
                        .HasColumnType("numeric")
                        .HasColumnName("target");

                    b.Property<DateTime?>("TargetMoldUsageDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("target_mold_usage_date");

                    b.Property<int?>("TransferLeadTime")
                        .HasColumnType("integer")
                        .HasColumnName("transfer_lead_time");

                    b.Property<string>("TrfNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trf_no");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("update_activity_data");
                });

            modelBuilder.Entity("PartsControlSystem.Models.UpdateActivityMatrix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("activity");

                    b.Property<bool>("Actual")
                        .HasColumnType("boolean")
                        .HasColumnName("actual");

                    b.Property<bool>("ApprovalLeadTime")
                        .HasColumnType("boolean")
                        .HasColumnName("approval_lead_time");

                    b.Property<bool>("FabricationLeadTime")
                        .HasColumnType("boolean")
                        .HasColumnName("fabrication_lead_time");

                    b.Property<bool>("LimitDate")
                        .HasColumnType("boolean")
                        .HasColumnName("limit_date");

                    b.Property<bool>("NeedOrNoNeed")
                        .HasColumnType("boolean")
                        .HasColumnName("need_no_need");

                    b.Property<bool>("PartsShortageDate")
                        .HasColumnType("boolean")
                        .HasColumnName("parts_shortage_date");

                    b.Property<bool>("RemainingDaysUntilLimit")
                        .HasColumnType("boolean")
                        .HasColumnName("remaining_days_until_limit");

                    b.Property<bool>("Remarks")
                        .HasColumnType("boolean")
                        .HasColumnName("remarks");

                    b.Property<bool>("Result")
                        .HasColumnType("boolean")
                        .HasColumnName("result");

                    b.Property<bool>("ResultEmailDateToSupplier")
                        .HasColumnType("boolean")
                        .HasColumnName("result_email_date_to_supplier");

                    b.Property<bool>("ResultPassedFailed")
                        .HasColumnType("boolean")
                        .HasColumnName("result_passed_failed");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("section");

                    b.Property<bool>("TRFNo")
                        .HasColumnType("boolean")
                        .HasColumnName("trf_no");

                    b.Property<bool>("Target")
                        .HasColumnType("boolean")
                        .HasColumnName("target");

                    b.Property<bool>("TargetMoldUsageDate")
                        .HasColumnType("boolean")
                        .HasColumnName("target_mold_usage_date");

                    b.Property<bool>("TransferLeadTime")
                        .HasColumnType("boolean")
                        .HasColumnName("transfer_lead_time");

                    b.HasKey("Id");

                    b.ToTable("update_activity_matrix");
                });

            modelBuilder.Entity("PartsControlSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ADID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adid");

                    b.Property<string>("ApproverRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("approver_role");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("authority");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employee_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("section");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PartsControlSystem.Models._4mForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ApprovedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_date");

                    b.Property<string>("AttachmentPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("attachment_path");

                    b.Property<string>("ChangeReason")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("change_reason");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("company_name");

                    b.Property<string>("ControlNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("control_number");

                    b.Property<bool>("HasReply")
                        .HasColumnType("boolean")
                        .HasColumnName("has_reply");

                    b.Property<bool>("IsEmailSent")
                        .HasColumnType("boolean");

                    b.Property<string>("PQCPIC")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pqc_pic");

                    b.Property<string>("PartCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("part_code");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("part_name");

                    b.Property<string>("PdfAttachmentPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SupplierPIC")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("supplier_pic");

                    b.Property<DateTime>("SupplierSubmissionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submission_date");

                    b.Property<DateTime>("TargetImplementationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("target_implementation_date");

                    b.Property<string>("TypeOfChange")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type_of_change");

                    b.HasKey("Id");

                    b.ToTable("4m_forms");
                });
#pragma warning restore 612, 618
        }
    }
}
