// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PartsControlSystem.Data;

#nullable disable

namespace PartsControlSystem.Migrations
{
    [DbContext(typeof(PostgreAppDbContext))]
    [Migration("20260107092300_addImportedData")]
    partial class addImportedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PartsControlSystem.Models.ImportData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BIPHMoldNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("biph_mold_no");

                    b.Property<string>("ChangeMaterial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("change_material");

                    b.Property<string>("ChildPartcode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("child_partcode");

                    b.Property<string>("ControlNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("control_no");

                    b.Property<DateTime>("DateImported")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_imported");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("MoldMaker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mold_maker");

                    b.Property<string>("MotherMoldCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mother_moldcode");

                    b.Property<string>("NewModel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_model");

                    b.Property<string>("NewToolingLocalization")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_tooling_localization");

                    b.Property<string>("NonConcurrent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("non_concurrent");

                    b.Property<string>("Other4M")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("other_4m");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("partname");

                    b.Property<string>("RenewalAdditionalMold")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("renewal_additional_mold");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supplier");

                    b.Property<string>("SupplierChangeLocalization")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supplier_change_localization");

                    b.Property<string>("SupplierMoldNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supplier_mold_no");

                    b.Property<string>("ToolingManagement")
                        .HasColumnType("text")
                        .HasColumnName("tooling_management");

                    b.Property<string>("TransferTooling")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transfer_tooling");

                    b.HasKey("Id");

                    b.ToTable("import_data");
                });

            modelBuilder.Entity("PartsControlSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ADID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adid");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("authority");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employee_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("section");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
