// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PartsControlSystem.Data;

#nullable disable

namespace PartsControlSystem.Migrations
{
    [DbContext(typeof(PostgreAppDbContext))]
    [Migration("20260429013617_AddLeadTimeDaysToNewToolingProcessMapping")]
    partial class AddLeadTimeDaysToNewToolingProcessMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PartsControlSystem.Models.ActivityCurrentProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ControlNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("control_number");

                    b.Property<string>("CurrentProcess")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_process");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id");

                    b.ToTable("activity_current_process");
                });

            modelBuilder.Entity("PartsControlSystem.Models.DE_Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ActualFinishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ControlNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentProcess")
                        .HasColumnType("text");

                    b.Property<string>("InputBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LeadTime")
                        .HasColumnType("text");

                    b.Property<string>("NeedNoNeed")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("de_evaluation");
                });

            modelBuilder.Entity("PartsControlSystem.Models.IQC_KatakenFinish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ActualFinishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ControlNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentProcess")
                        .HasColumnType("text");

                    b.Property<string>("InputBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("iqc_kataken_finish");
                });

            modelBuilder.Entity("PartsControlSystem.Models.IQC_KatakenSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ActualSubmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ControlNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentProcess")
                        .HasColumnType("text");

                    b.Property<string>("InputBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("iqc_kataken_submission");
                });

            modelBuilder.Entity("PartsControlSystem.Models.IQC_TestRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ActualFinishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ControlNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentProcess")
                        .HasColumnType("text");

                    b.Property<string>("InputBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ResultEmailDatetoSupplier")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResultPassedFailed")
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("iqc_test_run");
                });

            modelBuilder.Entity("PartsControlSystem.Models.ImportData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .HasColumnType("text")
                        .HasColumnName("activity");

                    b.Property<string>("BIPHMoldNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("biph_mold_no");

                    b.Property<string>("ChangeMaterial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("change_material");

                    b.Property<string>("ChildPartcode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("child_partcode");

                    b.Property<string>("ControlNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("control_no");

                    b.Property<DateTime>("DateImported")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_imported");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("MoldMaker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mold_maker");

                    b.Property<string>("MotherMoldCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mother_moldcode");

                    b.Property<string>("MultipleProcurementLocalization")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("multiple_procurement_localization");

                    b.Property<string>("NewModel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_model");

                    b.Property<string>("NewToolingLocalization")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_tooling_localization");

                    b.Property<string>("NonConcurrent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("non_concurrent");

                    b.Property<string>("Other4M")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("other_4m");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("partname");

                    b.Property<string>("ReasonOfChange")
                        .HasColumnType("text")
                        .HasColumnName("reason_of_change");

                    b.Property<string>("RenewalAdditionalMold")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("renewal_additional_mold");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("section");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supplier");

                    b.Property<string>("SupplierChangeLocalization")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supplier_change_localization");

                    b.Property<string>("SupplierMoldNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supplier_mold_no");

                    b.Property<string>("ToolingCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tooling_category");

                    b.Property<string>("ToolingManagement")
                        .HasColumnType("text")
                        .HasColumnName("tooling_management");

                    b.Property<string>("ToolingType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tooling_type");

                    b.Property<string>("TransferTooling")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transfer_tooling");

                    b.HasKey("Id");

                    b.ToTable("import_data");
                });

            modelBuilder.Entity("PartsControlSystem.Models.LeadTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("activity");

                    b.Property<decimal>("LeadTimeValue")
                        .HasColumnType("numeric")
                        .HasColumnName("lead_time");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("section");

                    b.HasKey("Id");

                    b.ToTable("LeadTimes");
                });

            modelBuilder.Entity("PartsControlSystem.Models.MP2_Capa_PDC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ControlNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InputBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("PartsShortageDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TargetMoldUsageDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("mp2_capa_pdc");
                });

            modelBuilder.Entity("PartsControlSystem.Models.MP2_ToolingFabrication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ActualFinishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ControlNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentProcess")
                        .HasColumnType("text");

                    b.Property<string>("FabricationLeadTime")
                        .HasColumnType("text");

                    b.Property<string>("InputBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("mp2_tooling_fabrication");
                });

            modelBuilder.Entity("PartsControlSystem.Models.MP2_ToolingPoIssuance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ActualIssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ControlNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentProcess")
                        .HasColumnType("text");

                    b.Property<string>("InputBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("TargetIssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("mp2_tooling_po_issuance");
                });

            modelBuilder.Entity("PartsControlSystem.Models.MP2_ToolingQuotationRequestApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ActualDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ControlNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentProcess")
                        .HasColumnType("text");

                    b.Property<string>("InputBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Process")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("mp2_tooling_qoutation_request");
                });

            modelBuilder.Entity("PartsControlSystem.Models.MP2_ToolingRequestOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ActualDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ControlNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentProcess")
                        .HasColumnType("text");

                    b.Property<string>("InputBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TRFNo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("mp2_tooling_request_order");
                });

            modelBuilder.Entity("PartsControlSystem.Models.MP2_ToolingTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ActualArrivalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ControlNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentProcess")
                        .HasColumnType("text");

                    b.Property<string>("InputBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("TargetArrivalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransferLeadTime")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("mp2_tooling_transfer");
                });

            modelBuilder.Entity("PartsControlSystem.Models.NewToolingCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ControlNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ControlNumber")
                        .IsUnique();

                    b.ToTable("new_tooling_category");
                });

            modelBuilder.Entity("PartsControlSystem.Models.NewToolingLocalizationProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ActualDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ControlNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentProcess")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("InputBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProcessStep")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Result")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ControlNumber", "Category", "ProcessStep")
                        .IsUnique();

                    b.ToTable("new_tooling_localization_process");
                });

            modelBuilder.Entity("PartsControlSystem.Models.NewToolingProcessMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProcessStep")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("new_tooling_process_mapping");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Multiple Procurement",
                            ProcessStep = "Mold LOA",
                            Section = "MP1-PUR",
                            StepOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Multiple Procurement",
                            ProcessStep = "Material LOA",
                            Section = "MP1-PUR",
                            StepOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Category = "Multiple Procurement",
                            ProcessStep = "Manual FC to new supplier",
                            Section = "MP2-DOM",
                            StepOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Category = "Multiple Procurement",
                            ProcessStep = "Tooling Transfer Date",
                            Section = "PUR-CTRL",
                            StepOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Category = "Multiple Procurement",
                            ProcessStep = "4M Application Date",
                            Section = "MP1-PUR",
                            StepOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Category = "Multiple Procurement",
                            ProcessStep = "Kataken PH Sample Submission",
                            Section = "IQC",
                            StepOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Category = "Multiple Procurement",
                            ProcessStep = "Kataken PH Sample Approval",
                            Section = "IQC",
                            StepOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            Category = "Multiple Procurement",
                            ProcessStep = "Availability of Parts Packaging Standard",
                            Section = "MP1-PUR",
                            StepOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            Category = "Multiple Procurement",
                            ProcessStep = "Open Sourcelist (New Supplier)",
                            Section = "MP1-PUR",
                            StepOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            Category = "Multiple Procurement",
                            ProcessStep = "Procurement Type Change",
                            Section = "MP1-PUR",
                            StepOrder = 10
                        },
                        new
                        {
                            Id = 11,
                            Category = "Multiple Procurement",
                            ProcessStep = "Test Run PO Request Date",
                            Section = "IQC",
                            StepOrder = 11
                        },
                        new
                        {
                            Id = 12,
                            Category = "Multiple Procurement",
                            ProcessStep = "Return of Special Procurement Type",
                            Section = "MP1-PUR",
                            StepOrder = 12
                        },
                        new
                        {
                            Id = 13,
                            Category = "Multiple Procurement",
                            ProcessStep = "Test Run PO Date",
                            Section = "MP2-DOM",
                            StepOrder = 13
                        },
                        new
                        {
                            Id = 14,
                            Category = "Multiple Procurement",
                            ProcessStep = "Test Run Delivery Date",
                            Section = "IQC",
                            StepOrder = 14
                        },
                        new
                        {
                            Id = 15,
                            Category = "Multiple Procurement",
                            ProcessStep = "Test Run Schedule",
                            Section = "IQC",
                            StepOrder = 15
                        },
                        new
                        {
                            Id = 16,
                            Category = "Multiple Procurement",
                            ProcessStep = "Test Run Approval Date",
                            Section = "IQC",
                            StepOrder = 16
                        },
                        new
                        {
                            Id = 17,
                            Category = "Multiple Procurement",
                            ProcessStep = "Quota Arrangement SAP Input",
                            Section = "MP1-PUR",
                            StepOrder = 17
                        },
                        new
                        {
                            Id = 18,
                            Category = "Multiple Procurement",
                            ProcessStep = "Confirmation of Parts Availability",
                            Section = "MP1-PUR",
                            StepOrder = 18
                        },
                        new
                        {
                            Id = 19,
                            Category = "Multiple Procurement",
                            ProcessStep = "Updated Price Input",
                            Section = "MP1-PUR",
                            StepOrder = 19
                        },
                        new
                        {
                            Id = 20,
                            Category = "Multiple Procurement",
                            ProcessStep = "PO Issuance Date (New Supplier)",
                            Section = "MP2-DOM",
                            StepOrder = 20
                        },
                        new
                        {
                            Id = 21,
                            Category = "Multiple Procurement",
                            ProcessStep = "Parts Delivery Date (New Supplier Delivery Date)",
                            Section = "MP2-DOM",
                            StepOrder = 21
                        },
                        new
                        {
                            Id = 22,
                            Category = "Supplier Change",
                            ProcessStep = "Mold LOA",
                            Section = "MP1-PUR",
                            StepOrder = 1
                        },
                        new
                        {
                            Id = 23,
                            Category = "Supplier Change",
                            ProcessStep = "Material LOA",
                            Section = "MP1-PUR",
                            StepOrder = 2
                        },
                        new
                        {
                            Id = 24,
                            Category = "Supplier Change",
                            ProcessStep = "Manual FC to new supplier",
                            Section = "PDC-Loc",
                            StepOrder = 3
                        },
                        new
                        {
                            Id = 25,
                            Category = "Supplier Change",
                            ProcessStep = "Tooling Transfer Date",
                            Section = "MP1-PUR",
                            StepOrder = 4
                        },
                        new
                        {
                            Id = 26,
                            Category = "Supplier Change",
                            ProcessStep = "4M Application Date",
                            Section = "MP1-PUR",
                            StepOrder = 5
                        },
                        new
                        {
                            Id = 27,
                            Category = "Supplier Change",
                            ProcessStep = "Kataken PH Sample Submission",
                            Section = "IQC",
                            StepOrder = 6
                        },
                        new
                        {
                            Id = 28,
                            Category = "Supplier Change",
                            ProcessStep = "Kataken PH Sample Approval",
                            Section = "IQC",
                            StepOrder = 7
                        },
                        new
                        {
                            Id = 29,
                            Category = "Supplier Change",
                            ProcessStep = "DE Sample Received Date",
                            Section = "DE",
                            StepOrder = 8
                        },
                        new
                        {
                            Id = 30,
                            Category = "Supplier Change",
                            ProcessStep = "DE Sample Approval",
                            Section = "DE",
                            StepOrder = 9
                        },
                        new
                        {
                            Id = 31,
                            Category = "Supplier Change",
                            ProcessStep = "QA Sample Received Date",
                            Section = "QA",
                            StepOrder = 10
                        },
                        new
                        {
                            Id = 32,
                            Category = "Supplier Change",
                            ProcessStep = "QA Sample Approval",
                            Section = "QA",
                            StepOrder = 11
                        },
                        new
                        {
                            Id = 33,
                            Category = "Supplier Change",
                            ProcessStep = "Availability of Parts Packaging Standard",
                            Section = "MP1-PUR",
                            StepOrder = 12
                        },
                        new
                        {
                            Id = 34,
                            Category = "Supplier Change",
                            ProcessStep = "Open Sourcelist (New Supplier)",
                            Section = "MP1-PUR",
                            StepOrder = 13
                        },
                        new
                        {
                            Id = 35,
                            Category = "Supplier Change",
                            ProcessStep = "Test Run PO Date",
                            Section = "MP2-DOM",
                            StepOrder = 14
                        },
                        new
                        {
                            Id = 36,
                            Category = "Supplier Change",
                            ProcessStep = "Test Run Delivery Date",
                            Section = "MP2-DOM",
                            StepOrder = 15
                        },
                        new
                        {
                            Id = 37,
                            Category = "Supplier Change",
                            ProcessStep = "Test Run Schedule",
                            Section = "IQC",
                            StepOrder = 16
                        },
                        new
                        {
                            Id = 38,
                            Category = "Supplier Change",
                            ProcessStep = "Test Run Approval Date",
                            Section = "IQC",
                            StepOrder = 17
                        },
                        new
                        {
                            Id = 39,
                            Category = "Supplier Change",
                            ProcessStep = "4M Approval Date",
                            Section = "IQC",
                            StepOrder = 18
                        },
                        new
                        {
                            Id = 40,
                            Category = "Supplier Change",
                            ProcessStep = "Simulation of Old Suppliers Stocks",
                            Section = "PDC-Loc",
                            StepOrder = 19
                        },
                        new
                        {
                            Id = 41,
                            Category = "Supplier Change",
                            ProcessStep = "SAP Setting Change",
                            Section = "MP1-PUR",
                            StepOrder = 20
                        },
                        new
                        {
                            Id = 42,
                            Category = "Supplier Change",
                            ProcessStep = "Final PO Delivery (Date)",
                            Section = "PDC-Loc",
                            StepOrder = 21
                        },
                        new
                        {
                            Id = 43,
                            Category = "Supplier Change",
                            ProcessStep = "BLK and FIX Supplier",
                            Section = "MP1-PUR",
                            StepOrder = 22
                        },
                        new
                        {
                            Id = 44,
                            Category = "Supplier Change",
                            ProcessStep = "Recosting Date",
                            Section = "MP1-PUR",
                            StepOrder = 23
                        },
                        new
                        {
                            Id = 45,
                            Category = "Supplier Change",
                            ProcessStep = "PO Issuance Date (New Supplier)",
                            Section = "PDC-Loc",
                            StepOrder = 24
                        },
                        new
                        {
                            Id = 46,
                            Category = "Supplier Change",
                            ProcessStep = "Parts Availability (New Supplier Delivery Date)",
                            Section = "PDC-Loc",
                            StepOrder = 25
                        },
                        new
                        {
                            Id = 47,
                            Category = "Localization",
                            ProcessStep = "Tooling PO Issued Date",
                            Section = "MP2-TOOL",
                            StepOrder = 1
                        },
                        new
                        {
                            Id = 48,
                            Category = "Localization",
                            ProcessStep = "CH Sample Submission Date",
                            Section = "IQC",
                            StepOrder = 2
                        },
                        new
                        {
                            Id = 49,
                            Category = "Localization",
                            ProcessStep = "CH Sample Approval Date",
                            Section = "IQC",
                            StepOrder = 3
                        },
                        new
                        {
                            Id = 50,
                            Category = "Localization",
                            ProcessStep = "Drawing Issuance to Supplier",
                            Section = "PC-DCI",
                            StepOrder = 4
                        },
                        new
                        {
                            Id = 51,
                            Category = "Localization",
                            ProcessStep = "Tooling Transfer Date",
                            Section = "MP1-PUR",
                            StepOrder = 5
                        },
                        new
                        {
                            Id = 52,
                            Category = "Localization",
                            ProcessStep = "4M Application Date",
                            Section = "MP1-PUR",
                            StepOrder = 6
                        },
                        new
                        {
                            Id = 53,
                            Category = "Localization",
                            ProcessStep = "Kataken PH Sample Submission",
                            Section = "IQC",
                            StepOrder = 7
                        },
                        new
                        {
                            Id = 54,
                            Category = "Localization",
                            ProcessStep = "Kataken PH Sample Approval",
                            Section = "IQC",
                            StepOrder = 8
                        },
                        new
                        {
                            Id = 55,
                            Category = "Localization",
                            ProcessStep = "Procurement Type Change",
                            Section = "PC-DCI",
                            StepOrder = 9
                        },
                        new
                        {
                            Id = 56,
                            Category = "Localization",
                            ProcessStep = "Open Sourcelist Local",
                            Section = "MP1-PUR",
                            StepOrder = 10
                        },
                        new
                        {
                            Id = 57,
                            Category = "Localization",
                            ProcessStep = "Test Run PO Request Date",
                            Section = "IQC",
                            StepOrder = 11
                        },
                        new
                        {
                            Id = 58,
                            Category = "Localization",
                            ProcessStep = "Test Run PO Date",
                            Section = "MP2-DOM",
                            StepOrder = 12
                        },
                        new
                        {
                            Id = 59,
                            Category = "Localization",
                            ProcessStep = "Test Run Delivery Date",
                            Section = "MP2-DOM",
                            StepOrder = 13
                        },
                        new
                        {
                            Id = 60,
                            Category = "Localization",
                            ProcessStep = "Test Run Schedule",
                            Section = "IQC",
                            StepOrder = 14
                        },
                        new
                        {
                            Id = 61,
                            Category = "Localization",
                            ProcessStep = "Test Run Approval Date",
                            Section = "IQC",
                            StepOrder = 15
                        },
                        new
                        {
                            Id = 62,
                            Category = "Localization",
                            ProcessStep = "4M Approval Date",
                            Section = "IQC",
                            StepOrder = 16
                        },
                        new
                        {
                            Id = 63,
                            Category = "Localization",
                            ProcessStep = "Simulation of Old Suppliers Stocks",
                            Section = "PDC-Loc",
                            StepOrder = 17
                        },
                        new
                        {
                            Id = 64,
                            Category = "Localization",
                            ProcessStep = "SAP Setting Change",
                            Section = "MP1-PUR",
                            StepOrder = 18
                        },
                        new
                        {
                            Id = 65,
                            Category = "Localization",
                            ProcessStep = "Final PO Delivery (Date)",
                            Section = "PDC-Loc",
                            StepOrder = 19
                        },
                        new
                        {
                            Id = 66,
                            Category = "Localization",
                            ProcessStep = "BLK and FIX Supplier",
                            Section = "MP1-PUR",
                            StepOrder = 20
                        },
                        new
                        {
                            Id = 67,
                            Category = "Localization",
                            ProcessStep = "Recosting Date",
                            Section = "MP1-PUR",
                            StepOrder = 21
                        },
                        new
                        {
                            Id = 68,
                            Category = "Localization",
                            ProcessStep = "Material Master Setting Change",
                            Section = "MP2-DOM",
                            StepOrder = 22
                        },
                        new
                        {
                            Id = 69,
                            Category = "Localization",
                            ProcessStep = "PO Issuance Date (New Supplier)",
                            Section = "MP2-DOM",
                            StepOrder = 23
                        },
                        new
                        {
                            Id = 70,
                            Category = "Localization",
                            ProcessStep = "Parts Availability (New Supplier Delivery Date)",
                            Section = "MP2-DOM",
                            StepOrder = 24
                        });
                });

            modelBuilder.Entity("PartsControlSystem.Models.QA_SpecialEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ActualFinishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ControlNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentProcess")
                        .HasColumnType("text");

                    b.Property<string>("InputBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LeadTime")
                        .HasColumnType("text");

                    b.Property<string>("NeedNoNeed")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("qa_special_evaluation");
                });

            modelBuilder.Entity("PartsControlSystem.Models.SQC_DFMQCDApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ActualFinishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovalLeadTime")
                        .HasColumnType("text");

                    b.Property<string>("ControlNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentProcess")
                        .HasColumnType("text");

                    b.Property<string>("InputBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NeedNoNeedQcdMtg")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("sqc_dfm_qcd_approval");
                });

            modelBuilder.Entity("PartsControlSystem.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartsCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("PartsControlSystem.Models.TransactionLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentProcess")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("InputDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PIC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TransactionLogs");
                });

            modelBuilder.Entity("PartsControlSystem.Models.UpdateActivityData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("activity");

                    b.Property<decimal?>("Actual")
                        .HasColumnType("numeric")
                        .HasColumnName("actual");

                    b.Property<int?>("ApprovalLeadTime")
                        .HasColumnType("integer")
                        .HasColumnName("approval_lead_time");

                    b.Property<string>("ControlNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("control_no");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<int?>("FabricationLeadTime")
                        .HasColumnType("integer")
                        .HasColumnName("fabrication_lead_time");

                    b.Property<DateTime?>("LimitDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("limit_date");

                    b.Property<string>("NeedNoNeed")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("need_no_need");

                    b.Property<DateTime?>("PartsShortageDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("parts_shortage_date");

                    b.Property<int?>("RemainingDaysUntilLimit")
                        .HasColumnType("integer")
                        .HasColumnName("remaining_days_until_limit");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("result");

                    b.Property<DateTime?>("ResultEmailDateToSupplier")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("result_email_date_to_supplier");

                    b.Property<string>("ResultPassedFailed")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("result_passed_failed");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("section");

                    b.Property<decimal?>("Target")
                        .HasColumnType("numeric")
                        .HasColumnName("target");

                    b.Property<DateTime?>("TargetMoldUsageDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("target_mold_usage_date");

                    b.Property<int?>("TransferLeadTime")
                        .HasColumnType("integer")
                        .HasColumnName("transfer_lead_time");

                    b.Property<string>("TrfNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trf_no");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("update_activity_data");
                });

            modelBuilder.Entity("PartsControlSystem.Models.UpdateActivityMatrix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("activity");

                    b.Property<bool>("Actual")
                        .HasColumnType("boolean")
                        .HasColumnName("actual");

                    b.Property<bool>("ApprovalLeadTime")
                        .HasColumnType("boolean")
                        .HasColumnName("approval_lead_time");

                    b.Property<bool>("FabricationLeadTime")
                        .HasColumnType("boolean")
                        .HasColumnName("fabrication_lead_time");

                    b.Property<bool>("LimitDate")
                        .HasColumnType("boolean")
                        .HasColumnName("limit_date");

                    b.Property<bool>("NeedOrNoNeed")
                        .HasColumnType("boolean")
                        .HasColumnName("need_no_need");

                    b.Property<bool>("PartsShortageDate")
                        .HasColumnType("boolean")
                        .HasColumnName("parts_shortage_date");

                    b.Property<bool>("RemainingDaysUntilLimit")
                        .HasColumnType("boolean")
                        .HasColumnName("remaining_days_until_limit");

                    b.Property<bool>("Remarks")
                        .HasColumnType("boolean")
                        .HasColumnName("remarks");

                    b.Property<bool>("Result")
                        .HasColumnType("boolean")
                        .HasColumnName("result");

                    b.Property<bool>("ResultEmailDateToSupplier")
                        .HasColumnType("boolean")
                        .HasColumnName("result_email_date_to_supplier");

                    b.Property<bool>("ResultPassedFailed")
                        .HasColumnType("boolean")
                        .HasColumnName("result_passed_failed");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("section");

                    b.Property<bool>("TRFNo")
                        .HasColumnType("boolean")
                        .HasColumnName("trf_no");

                    b.Property<bool>("Target")
                        .HasColumnType("boolean")
                        .HasColumnName("target");

                    b.Property<bool>("TargetMoldUsageDate")
                        .HasColumnType("boolean")
                        .HasColumnName("target_mold_usage_date");

                    b.Property<bool>("TransferLeadTime")
                        .HasColumnType("boolean")
                        .HasColumnName("transfer_lead_time");

                    b.HasKey("Id");

                    b.ToTable("update_activity_matrix");
                });

            modelBuilder.Entity("PartsControlSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ADID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adid");

                    b.Property<string>("ApproverRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("approver_role");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("authority");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employee_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("section");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PartsControlSystem.Models.ViewActivityMonitoring", b =>
                {
                    b.Property<string>("ControlNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("de_finish_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("de_lead_time")
                        .HasColumnType("text");

                    b.Property<string>("de_need")
                        .HasColumnType("text");

                    b.Property<string>("de_remarks")
                        .HasColumnType("text");

                    b.Property<string>("de_result")
                        .HasColumnType("text");

                    b.Property<DateTime?>("fab_finish_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("fab_lead_time")
                        .HasColumnType("text");

                    b.Property<string>("fab_remarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("kataken_finish_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("kataken_remarks")
                        .HasColumnType("text");

                    b.Property<string>("kataken_result")
                        .HasColumnType("text");

                    b.Property<DateTime?>("kataken_submission_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("kataken_submission_remarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("parts_shortage_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("po_actual_issue_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("po_remarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("po_target_issue_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("qa_finish_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("qa_lead_time")
                        .HasColumnType("text");

                    b.Property<string>("qa_need")
                        .HasColumnType("text");

                    b.Property<string>("qa_remarks")
                        .HasColumnType("text");

                    b.Property<string>("qa_result")
                        .HasColumnType("text");

                    b.Property<DateTime?>("qr_actual_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("qr_remarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("qr_target_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("sqc_finish_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("sqc_lead_time")
                        .HasColumnType("text");

                    b.Property<string>("sqc_need_qcd")
                        .HasColumnType("text");

                    b.Property<string>("sqc_remarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("target_mold_usage_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("test_run_email_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("test_run_finish_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("test_run_pass_fail")
                        .HasColumnType("text");

                    b.Property<string>("test_run_remarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("transfer_actual_arrival")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("transfer_lead_time")
                        .HasColumnType("text");

                    b.Property<string>("transfer_remarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("transfer_target_arrival")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("tro_actual_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("tro_remarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("tro_target_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("tro_trf_no")
                        .HasColumnType("text");

                    b.ToTable((string)null);

                    b.ToView("view_activity_monitoring", "public");
                });

            modelBuilder.Entity("PartsControlSystem.Models._4mForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ApprovedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_date");

                    b.Property<string>("AttachmentPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("attachment_path");

                    b.Property<string>("ChangeReason")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("change_reason");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("company_name");

                    b.Property<string>("ControlNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("control_number");

                    b.Property<bool>("HasReply")
                        .HasColumnType("boolean")
                        .HasColumnName("has_reply");

                    b.Property<bool>("IsEmailSent")
                        .HasColumnType("boolean");

                    b.Property<string>("PQCPIC")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pqc_pic");

                    b.Property<string>("PartCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("part_code");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("part_name");

                    b.Property<string>("PdfAttachmentPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SupplierPIC")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("supplier_pic");

                    b.Property<DateTime>("SupplierSubmissionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submission_date");

                    b.Property<DateTime>("TargetImplementationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("target_implementation_date");

                    b.Property<string>("TypeOfChange")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type_of_change");

                    b.HasKey("Id");

                    b.ToTable("4m_forms");
                });
#pragma warning restore 612, 618
        }
    }
}
